name: Daily Panchang Generate

on:
  schedule:
    - cron: "31 18 * * *"   # 00:01 IST
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Generate today.json
        run: node generate.js

      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@mail.com"
          git add public/today.json
          git commit -m "update today.json" || echo "no changes"
          git push
